### ISSUE TITLE
Lack of Docstrings

### ISSUE THREAD

**Issue by lights-a5** [NandaScott/Scrython#3]
Docstrings provides an easy way to get help about python modules without having to resort to online. Just rummaging around in your code I noticed that none of your classes, methods, or functions have any. Perhaps it would be best to put this documentation in your code?

**Comment by NandaScott** [comment]
That is definitely something to add. Thanks for the notice.

**Comment by NandaScott** [comment]
I've updated /cards/ on develop to have docstrings. They include all Positional/Optional arguments, Attributes, and Examples.

https://github.com/NandaScott/Scrython/tree/develop/scrython/cards

**Comment by NandaScott** [comment]
Alrighty pushed a bunch of docstrings to develop. Closing issue.
