### ISSUE TITLE
KeyError: "This card has no key 'oracle_text'" for transformable cards

### ISSUE THREAD

**Issue by LordPCX** [NandaScott/Scrython#42]
I use Spyder with Python 3.7. This following example program leads to an error for transformable cards like "Delver of secrets":

import scrython
import time
import nest_asyncio
nest_asyncio.apply()
time.sleep(0.05)
query="Delver of Secrets"
curCard=scrython.cards.Named(exact=query)
print(curCard.name())
print(curCard.oracle_text())

I did not see how I could/should treat such cards in the docs. I'm always getting:
KeyError: "This card has no key 'oracle_text'"

**Comment by NandaScott** [comment]
The oracle text for transform cards is stored in `card.card_faces()`. Then from there you'd grab the key as `card.card_faces()[0]['oracle_text']`. It's not sleek, and I should really fix that but I can't give a timeline to when that will happen.
