### ISSUE TITLE
Cards with the adventure layout aren't properly accessing "image_uris()"

### ISSUE THREAD

**Issue by TallPatrick** [NandaScott/Scrython#46]
Hello,

I wrote a little script that pulls down card images for display on a stream.  I encountered a bug that I worked around by adding a new feature, but I still think it is worth mentioning.

When getting a card with adventure, you're unable to get the image_uris() to return anything.  Here's some example code:
```
import scrython
card = scrython.cards.Named(exact='Decorated Knight')
card.image_uris()
```

I think this is a bug in Scrython because if you look at the card.uri(), which is in this case [https://api.scryfall.com/cards/6cbda4a6-e01b-4df2-aee9-b6f14336b85f](url), the image_uris() exist within the JSON file there.

Let me know if you see the same issue.  Also let me know if I'm just using this wrong, but this method has worked and continues to work for non-adventure cards.

**Comment by NandaScott** [comment]
Thanks for bringing this to my attention, I'll check it out tomorrow and
try to find time for a fix this week.

**Comment by NandaScott** [comment]
I've just tested your example and I couldn't reproduce the issue. Could you get me some more details?

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.        
>>> import scrython
>>> card = scrython.cards.Named(exact='Decorated Knight')
>>> card.image_uris()
{'small': 'https://img.scryfall.com/cards/small/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.jpg?1577374934', 'normal': 'https://img.scryfall.com/cards/normal/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.jpg?1577374934', 'large': 
'https://img.scryfall.com/cards/large/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.jpg?1577374934', 'png': 'https://img.scryfall.com/cards/png/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.png?1577374934', 'art_crop': 'https://img.scryfall.com/cards/art_crop/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.jpg?1577374934', 'border_crop': 'https://img.scryfall.com/cards/border_crop/front/6/c/6cbda4a6-e01b-4df2-aee9-b6f14336b85f.jpg?1577374934'}
>>>

**Comment by TallPatrick** [comment]
I just tested again and also couldn't reproduce the issue.

I'm betting it was an error on the side of scryfall's API.

I'll close this thread.
