### ISSUE TITLE
Should we rate limit?

### ISSUE THREAD

**Issue by lights-a5** [NandaScott/Scrython#5]
Scryfall has a rate limit to their API.

["We kindly ask that you insert 50 – 100 milliseconds of delay between the requests you send to the server. (i.e., 10 requests per second on average)."](https://scryfall.com/docs/api)

There is a library that is useful that can rate limit functions called [ratelimit](https://pypi.python.org/pypi/ratelimit/1.1.0). Which essentially sleeps functions you decorate it with until it is no longer at the limit. Pretty useful honestly.

The debate though is whether we should rate limit inside this wrapper or have it be the responsibility of whomever wants to use the wrapper.

**Comment by NandaScott** [comment]
I feel that would be the responsibility of the user. Having a universal rate limit wouldn't be necessary for all projects, and limiting it is pretty simple to accomplish. This should definitely be documented, possibly in the README.

**Comment by NandaScott** [comment]
Added a note about rate limiting in the README docs in the develop branch.
