### ISSUE TITLE
KeyError with oracle_text

### ISSUE THREAD

**Issue by pyrometheous** [NandaScott/Scrython#57]
Using the card "Bonecrusher Giant" and the following script:

``` python
card = scrython.cards.Named(fuzzy="Bonecrusher Giant")
text = card.oracle_text()
```

I'm getting:
```
KeyError: "This card has no key 'oracle_text'"
```

**Comment by NandaScott** [comment]
This is because the oracle text for adventure cards is actually in the `card_faces` array. So the way you would access them is

```
card.card_faces()[0]['oracle_text']
```

I suppose there's an argument to be made that `oracle_text` could just grab the front face of the card if provided no index.

**Comment by pyrometheous** [comment]
Thank you for the clarification.
