### ISSUE TITLE
Missing power, toughness, loyalty, and falvor_text attributes 

### ISSUE THREAD

**Issue by Mendess2526** [NandaScott/Scrython#7]
That's just it. The CardObject class is missing the missing power, toughness, loyalty, and falvor_text attributes

**Comment by bmbowdish** [comment]
Does this mean that if I create a creature object from Swiftfall.card(“Tarmogoyf”) it’s power and toughness aren’t tracked?

**Comment by NandaScott** [comment]
It just means that I forgot to add a way to access it. If you use `card.scryfallJson['power']` you can still access the power value.

I'll add this in the next update but I'm working on issue #6 right now, unless someone makes a pull request directly to develop branch.

**Comment by NandaScott** [comment]
Closing issue, solved from pull request #9
