### ISSUE TITLE
Transform Cards

### ISSUE THREAD

**Issue by AndrewWigman** [NandaScott/Scrython#71]
So I'm new to python in general, let alone using Scrython.

I have managed to achieve most of the things I have bee attempting, but I'm struggling with transform cards, specifically in my testing Bloodline Keeper. I have gotten work a round working for some of my functions but when trying to get the mana_cost  it falls down. so I'm putting in an if to check the card face and getting back the following.

`[{'object': 'card_face', 'name': 'Bloodline Keeper', 'mana_cost': '{2}{B}{B}', 'type_line': 'Creature — Vampire', 'oracle_text': 'Flying\n{T}: Create a 2/2 black Vampire creature token with flying.\n{B}: Transform Bloodline Keeper. Activate only if you control five or more Vampires.', 'colors': ['B'], 'power': '3', 'toughness': '3', 'artist': 'Jason Chan', 'artist_id': '8062d5a9-51b6-4822-933f-fa9e9dba8416', 'illustration_id': 'a30b5d9b-b969-4308-9184-e1b8861b967a', 'image_uris': {'small': 'https://c1.scryfall.com/file/scryfall-cards/small/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'normal': 'https://c1.scryfall.com/file/scryfall-cards/normal/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'large': 'https://c1.scryfall.com/file/scryfall-cards/large/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'png': 'https://c1.scryfall.com/file/scryfall-cards/png/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.png?1562826506', 'art_crop': 'https://c1.scryfall.com/file/scryfall-cards/art_crop/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'border_crop': 'https://c1.scryfall.com/file/scryfall-cards/border_crop/front/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506'}}, {'object': 'card_face', 'name': 'Lord of Lineage', 'mana_cost': '', 'type_line': 'Creature — Vampire', 'oracle_text': 'Flying\nOther Vampire creatures you control get +2/+2.\n{T}: Create a 2/2 black Vampire creature token with flying.', 'colors': ['B'], 'color_indicator': ['B'], 'power': '5', 'toughness': '5', 'artist': 'Jason Chan', 'artist_id': '8062d5a9-51b6-4822-933f-fa9e9dba8416', 'illustration_id': '87c28b97-670f-491c-9288-c2abe06f2403', 'image_uris': {'small': 'https://c1.scryfall.com/file/scryfall-cards/small/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'normal': 'https://c1.scryfall.com/file/scryfall-cards/normal/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'large': 'https://c1.scryfall.com/file/scryfall-cards/large/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'png': 'https://c1.scryfall.com/file/scryfall-cards/png/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.png?1562826506', 'art_crop': 'https://c1.scryfall.com/file/scryfall-cards/art_crop/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506', 'border_crop': 'https://c1.scryfall.com/file/scryfall-cards/border_crop/back/1/3/13896468-e3d0-4bcb-b09e-b5c187aecb03.jpg?1562826506'}}]
`

so `card.card_faces()` cant be `.split()`. so how can i split it into 2 lists by the objects? I tried looking around the internet for some general python answers, but I couldn't find anything that works. also can I index the list by `{object:......`? cause `cards.card_faces(1)` didnt work.

Sorry for such a Noob question, I may have just been staring at this to long and am missing something.

**Comment by NandaScott** [comment]
Don't worry about noob questions. Everyone starts somewhere 😄 

So if you want the `mana_cost` (or any other key for that matter) you have a few options.

1. Since `card_faces()` returns an array you can access an individual dictionary by adding an index: `card_faces()[0]` which will return the first face, etc.
2. If you want to loop over each face you can do the same thing but replace the index with your iterator: `card_faces()[i]`
3. You can also destructure each face in their own variable and you can work with then individually:

```face1, face2 = card_faces()```
`face1['mana_cost']`

This would break in the future if WoTC somehow figure out how to put 3 faces on a card though.

**Comment by AndrewWigman** [comment]
Oh...... that makes sense. 

I've used arrays in my script already, but apparently my brain didn't think  `( )[ ]` was viable syntax.

I should hopefully be able to resolve my code mistakes now 🗡️ 

Thank you for the help

**Comment by NandaScott** [comment]
No problem! Python can let you do silly stuff like that, though that does come at the cost of readability.
