### ISSUE TITLE
scrython keyerror: 'mana_cost'

### ISSUE THREAD

**Issue by CodingBDX** [NandaScott/Scrython#74]
well i made script who search inside file txt and put price, set_name, mana_cost
but values mana_cost crash my script and put keyerror depeending of cards

str(card["mana_cost"])

coul you tell me the good code for all cards pass without error**

thank all

**Comment by NandaScott** [comment]
The only place that a card doesn't readily have a `mana_cost` key is if that card has multiple faces. In which case you can find that card in `card_faces`.

The relevant methods are [mana_cost()](https://github.com/NandaScott/Scrython/blob/master/docs/scrython.cards/Named.md#mana_cost) and [card_faces()](https://github.com/NandaScott/Scrython/blob/master/docs/scrython.cards/Named.md#card_faces)

**Comment by bibiyanki2** [comment]
Si i write
Str(card_faces['mana_cost'])

It s good?

**Comment by bibiyanki2** [comment]
so friend,i test it with 2 arguments card and card_faces
it's work for lt card but i don't understand we have problem with card "fury", that not work

`1 fury
 4 Bloodstained Mire
3 Copperline Gorge
3 Mountain
3 Stomping Ground
4 Wooded Foothills
4 Blazing Rootwalla
4 Burning Inquiry
3 Cathartic Reunion
4 Dragon's Rage Channeler
4 Flameblade Adept
4 Goblin Lore
4 Hollow One
4 Lightning Bolt
3 Ox of Agonas
4 Street Wraith
1 Tarfire
4 Vengevine

Sideboard:
2 Ancient Grudge
3 Blood Moon
2 Foundation Breaker

2 Lightning Axe
2 Seasoned Pyromancer
2 Tormod's Crypt



`


remove fury that work perfect

**Comment by NandaScott** [comment]
Sorry I haven't kept up with this thread.

If a card does not have a `card_faces` key in the response object then the `card_faces()` method will throw a key error.

Please read the documentation thoroughly and I'm sure you'll find your answer there. Closing this issue.
